version: '3'
services:
  django_mysql:
    container_name: django-mysql
    image: mysql/mysql-server:8.0.27
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: dj
      MYSQL_ROOT_PASSWORD: ThisisP@ssw0rd
      MYSQL_ROOT_HOST: '%'
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - /opt/docker-volumes/mysql:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - dj

  dj_web:
    container_name: dj-web
    build: .
    command: gunicorn backend_act.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120 --log-level=debug
    # command: python manage.py runserver --settings=backend_act.setting_prod
    volumes:
      - /opt/docker-volumes/dj-static:/code/static
      - /opt/docker-volumes/media:/code/media
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - django_mysql
    networks:
      - dj

networks:
  dj: